### ISSUE TITLE
Uncaught Error: Cannot send message to terminated process

### ISSUE THREAD

**Issue by goroakimoto** [f/atom-term2#105] opened 2015-04-10 06:46 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.9.5
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.5

### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /Applications/Atom.app/Contents/Resources/app/src/task.js:110

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app/src/task.js:110:15)
  at TermView.input (/Users/akimoto/.atom/packages/term2/lib/TermView.coffee:70:17)
  at TermView.paste (/Users/akimoto/.atom/packages/term2/lib/TermView.coffee:107:6)
  at atom-workspace.<anonymous> (/Users/akimoto/.atom/packages/term2/lib/TermView.coffee:89:60)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
  2x -0:58.7 core:move-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
 14x -0:56.1 core:backspace (div.terminal)
  2x -0:51.1 core:confirm (div.terminal)
     -0:39.7 term2:copy (div.terminal)
     -0:37.7 core:paste (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:37.1 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:36.4 core:move-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:36.0 core:backspace (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:35.4 core:paste (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:32.4 core:backspace (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:29.3 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:27.5 core:move-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:27.3 core:move-left (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:26.5 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:01.4 term2:copy (div.terminal)
     -0:01.0 term2:paste (div.terminal)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "term2": {
    "colors": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
file-icons, v1.5.2
highlight-selected, v0.9.1
localization, v1.16.1
recent-files, v0.3.0
script, v2.18.0
show-ideographic-space, v0.1.6
term2, v0.9.5

# Dev
No dev packages
```

**Comment by MoOx** [comment] 2015-04-17 08:21
Getting it too.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.2
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.5

### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/task.js:110

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/task.js:110:15)
  at TermView.input (/Users/MoOx/.atom/packages/term2/lib/TermView.coffee:70:17)
  at TermView.paste (/Users/MoOx/.atom/packages/term2/lib/TermView.coffee:107:6)
  at atom-workspace.<anonymous> (/Users/MoOx/.atom/packages/term2/lib/TermView.coffee:89:60)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:48.6 editor:select-to-end-of-line (atom-text-editor.editor)
     -0:46.2 core:save (atom-text-editor.editor)
     -0:44.2 core:move-down (atom-text-editor.editor)
 10x -0:43.9 editor:move-to-beginning-of-word (atom-text-editor.editor)
  3x -0:42.3 core:move-right (atom-text-editor.editor)
  2x -0:41.7 core:backspace (atom-text-editor.editor)
     -0:39.3 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:39.0 core:move-left (atom-text-editor.editor)
  2x -0:38.6 core:backspace (atom-text-editor.editor)
  2x -0:38.0 core:save (atom-text-editor.editor)
     -0:29.2 core:move-up (div.terminal)
     -0:28.8 term2:copy (div.terminal)
     -0:28.3 core:move-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:27.8 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:02.4 term2:copy (div.terminal)
     -0:01.7 term2:paste (div.terminal)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/MoOx/Sync/Development",
    "disabledPackages": [
      "language-mustache",
      "welcome",
      "language-toml",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-php",
      "language-perl",
      "language-objective-c",
      "language-less",
      "language-java",
      "language-hyperlink",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-jsx"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "term2": {
    "colors": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.6.0
linter, v0.12.0
linter-eslint, v0.5.2
open-last-project, v0.4.1
project-manager, v1.15.5
react, v0.11.4
term2, v0.9.5
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by MoOx** [comment] 2015-04-17 10:03
I just find how to reproduce while I was creating an other issue

http://cl.ly/0b0c3B3S323L/issue-atom-term2.mov

**Comment by bvhme** [comment] 2015-05-29 10:27
I have this issue whenever I paste anything into Term2

**Comment by Ortuna** [comment] 2015-06-27 13:40
:+1:  paste issue for me too

**Comment by serapath** [comment] 2015-07-05 00:38
have the same problem

**Comment by ashoda** [comment] 2015-07-15 18:45
+1

**Comment by thejayvm** [comment] 2015-07-21 04:42
I get this when opening or closing(exit) a terminal tab.

**Comment by rdiaz82** [comment] 2015-07-21 12:23
+1

**Comment by mikelax** [comment] 2015-07-21 23:22
I received this issue with the following repro steps:
Mac OS:  10.10.4
Atom:  1.0.2
term2:  0.9.14

Keyboard shortcut Ctrl, alt, down arrow
Interesting, that the shortcut Ctrl, alt, t  works fine and does not cause this error. 

Here is the output that I see in the newly opened down split tab, but this same error message is displayed on the regular new tab as well so it might be a red herring. 

bash: brew: command not found

**Comment by joshcoody** [comment] 2015-07-22 03:36
I have the paste issue, and also the closing terminal tab issue.

**Comment by kriox26** [comment] 2015-07-22 05:19
I also have the closing terminal tab issue

**Comment by gatisdukurs** [comment] 2015-07-22 16:11
I have this too.

**Comment by KINFOO** [comment] 2015-07-24 14:55
:+1:

**Comment by MoOx** [comment] 2015-07-27 14:00
This happens when a process call `exit`. I will add a note in the README until we do something more clear.

**Comment by djsly** [comment] 2015-07-30 02:15
Getting this error everytime I enlarge the term panel or that I open a new one.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.14


### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:122

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:122:15)
  at TermView.resize (/Users/sylvain_boily/.atom/packages/term2/lib/TermView.coffee:77:17)
  at TermView.resizeToPane (/Users/sylvain_boily/.atom/packages/term2/lib/TermView.coffee:146:6)
  at /Users/sylvain_boily/.atom/packages/term2/lib/TermView.coffee:125:72

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "term2": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
color-picker, v2.0.11
highlight-selected, v0.10.1
react, v0.12.6
svn, v0.0.7
term2, v0.9.14

# Dev
No dev packages
```

**Comment by chrisnesbit1** [comment] 2015-07-31 18:36
+1 happens on paste for me

**Comment by gbailey4** [comment] 2015-08-04 03:21
Happens on paste for me, too. OS X 10.10.4.

**Comment by tylerFowler** [comment] 2015-08-05 21:50
I find that I get this whenever I split a tab, or if any package splits a tab (i.e. Git Plus commit), even if that new split tab is a term2 tab.

**Comment by xasx** [comment] 2015-08-06 09:14
Ctrl+D-ing also shows this error message.

**Comment by samatcd** [comment] 2015-08-06 09:49
I got this when resizing the split tab.

**Comment by prometheas** [comment] 2015-08-06 21:22
+1 happened when I attempted to close the terminal pane.

**Comment by xasx** [comment] 2015-08-07 07:00
@MoOx I wonder whether resizing temporarily closes the terminal/shell - does it?

**Comment by tylerFowler** [comment] 2015-08-07 15:36
That could be, it only seems to happen after I've opened a shell at least once in that particular Atom session (including when I have no terminal shells open). Perhaps the window isn't being properly destroyed?

**Comment by MoOx** [comment] 2015-08-08 20:07
Don't have an idea yet, I am new to this plugin and I hate coffeescript :)

**Comment by diegognt** [comment] 2015-08-10 15:55
+1

**Comment by xasx** [comment] 2015-08-11 07:06
I apparently only get this when using term2 in a Pane, not in a Tab:

[Enter steps to reproduce below:]

1a. Open term2 in a pane, or
1b. Close the pane

**Atom Version**: 1.0.5
**System**: "Fedora release
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.14


### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /usr/share/atom/resources/app.asar/src/task.js:122

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/usr/share/atom/resources/app.asar/src/task.js:122:15)
  at TermView.resize (/home/aschoeneck/.atom/packages/term2/lib/TermView.coffee:77:17)
  at TermView.resizeToPane (/home/aschoeneck/.atom/packages/term2/lib/TermView.coffee:146:6)
  at /home/aschoeneck/.atom/packages/term2/lib/TermView.coffee:125:72

```

### Commands

```
     -0:57.2.0 term2:open (atom-text-editor.editor.is-focused)
  2x -0:48.6.0 core:confirm (div.terminal)
     -0:35.8.0 term2:open-split-down (atom-workspace.workspace.scrollbars-visible-always.theme-github-2014.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel"
    ],
    "themes": [
      "atom-material-ui",
      "github-2014"
    ]
  },
  "term2": {}
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.13
file-icons, v1.6.3
fonts, v0.6.0
git-tab-status, v1.9.2
github-2014, v3.9.0
language-csharp, v0.7.0
language-docker, v1.1.3
language-groovy, v0.4.0
markdown-format, v2.5.1
minimap, v4.12.2
minimap-git-diff, v4.1.7
pdf-view, v0.23.0
pretty-json, v0.4.1
tabular, v0.1.0
term2, v0.9.14

# Dev
No dev packages
```

**Comment by spbrien** [comment] 2015-08-13 12:54
Having the same issue here. Here are some details:

[Enter steps to reproduce below:]

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.3
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.15

### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/task.js:122

Error: Cannot send message to terminated process
    at Task.module.exports.Task.send (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/task.js:122:15)
    at TermView.resize (~/.atom/packages/term2/lib/TermView.coffee:130:30)
    at TermView.resizeToPane (~/.atom/packages/term2/lib/TermView.coffee:247:12)
    at ~/.atom/packages/term2/lib/TermView.coffee:213:26
```

### Commands

```
     -0:02.1.0 pane:split-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

**Comment by diegognt** [comment] 2015-08-14 20:49
+1

**Comment by OJFord** [comment] 2015-08-16 22:48
+1

**Comment by mico** [comment] 2015-08-18 15:50
getting this error when trying to resize plantuml-viewer preview tab

**Comment by raguilera82** [comment] 2015-08-26 14:57
+1

**Comment by FedericoGinosa** [comment] 2015-08-28 00:41
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.8
**System**: Mac OS X 10.10.4
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.15


### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120:15)
  at TermView.resize (/Users/federico/.atom/packages/term2/lib/TermView.coffee:77:17)
  at TermView.resizeToPane (/Users/federico/.atom/packages/term2/lib/TermView.coffee:157:6)
  at /Users/federico/.atom/packages/term2/lib/TermView.coffee:136:72

```

### Commands

```
  4x -7:25.8.0 core:move-up (div.terminal)
     -7:21.6.0 term2:copy (div.terminal)
  3x -7:20.9.0 term2:paste (div.terminal)
     -6:36 settings-view:open (atom-pane.pane.active)
     -4:39.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:28.4.0 term2:paste (div.terminal)
     -1:16.5.0 term2:open (div.settings-view.pane-item)
     -1:11.3.0 core:confirm (div.terminal)
     -1:10.6.0 term2:paste (div.terminal)
     -1:04.8.0 term2:copy (div.terminal)
     -1:03.5.0 core:confirm (div.terminal)
     -1:01.2.0 term2:copy (div.terminal)
     -1:01.0 term2:paste (div.terminal)
     -0:14.9.0 term2:copy (div.terminal)
     -0:09.1.0 core:close (atom-pane.pane.active)
     -0:01.1.0 term2:open-split-down (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {},
  "term2": {
    "autoRunCommand": "login -f $(whoami)"
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.4.3
linter-jshint, v1.1.5
term2, v0.9.15

# Dev
No dev packages
```

**Comment by FedericoGinosa** [comment] 2015-08-28 00:49
```
npm install -g pty
```
It works like a charm

**Comment by samatcd** [comment] 2015-08-28 02:13
@FedericoGinosa, this works perfectly, thanks!

**Comment by tylerFowler** [comment] 2015-08-29 19:04
This actually did not work for me.. still seems to be happening after installing `pty`

**Comment by f** [comment] 2015-08-30 23:30
It says "cannot send a message to terminated process" means a race condition which is a really minor problem for Term2. It basically says "you closed the terminal but still want to send some resize commands to it". I just put a `try` to suppress the error.

**Closed by f** 2015-08-30 23:30 UTC
Labels: enhancement, help wanted

**Comment by prometheas** [comment] 2015-08-31 19:10
Seems solved for me :) nice one.

**Comment by MoOx** [comment] 2015-09-01 04:45
@f maybe instead of making the error silent we should correctly stop listening for some events to not even trigger the call?
