### ISSUE TITLE
Broken pane/tab navigation

### ISSUE THREAD

**Issue by jdsimcoe** [f/atom-term2#6] opened 2014-05-15 14:46 UTC
I often navigate tabs using `cmd` + `shift` + `]` and `cmd` + `shift` + `[`. I can navigate away from the terminal window when it first opens but when I navigate back the Terminal breaks my navigation. It also breaks the key command to open inspector (`opt` + `cmd` + `i`). Any chance of looking into this?

Thanks for the awesome work!

**Comment by MoOx** [comment] 2015-07-01 12:02
Need some help for this ?

**Comment by bojidar-bg** [comment] 2015-07-02 07:38
FYI, `control-tab` and `shift-control-tab` work ...

**Comment by MoOx** [comment] 2015-07-02 08:16
When I navigate in Atom between window panes using cmd+k/cmd+arrows, I don't get the focus in the terminal.

**Comment by f** [comment] 2015-08-30 23:08
Cannot reproduce this error anymore. Closing. Please reopen if occurs.

**Comment by MoOx** [comment] 2015-09-01 04:51
I am able to reproduce. Just open a term2 tab, then go in a file tab, then do cmd+k + cmd+(arrow to access the term2 tab). You will get focus on the tab itself, but not in the terminal (if you type, you don't have any chars because the focus is not really in the term).

**Comment by jichu4n** [comment] 2015-10-09 02:23
I've sent out PR #199 which should address this by binding to Atom's Pane and Pane Item activation events. PTAL?

**Comment by lebedov** [comment] 2016-03-27 16:02
Observation re atom 1.6.0: when I tried installing 0f3a1ca of atom-term2 in a fresh .atom directory (i.e., no other custom packages installed), I was able to open/use the terminal and switch to/from the terminal with my mouse, but switching from the terminal to an editor pane with ``pane:show-next-item`` or ``pane:show-previous-item`` would cause atom to hang.

**Closed** 2017-02-16 06:41 UTC
Labels: bug
